### ISSUE TITLE
Failed to find Build Tools revision 23.0.2

### ISSUE THREAD

**Issue by saeedvz** [CentaurWarchief/react-native-android-sms-listener#23]
I got this error on react-native 0.47.0

**Comment by sbbeez** [comment]
hey!! Just resolved the same issue that I had!! this is because the compiled version of Android is 23.0.3 where the lib required a minimum of 25.0.0! so to resolve it : 
search in whole project as "23.0.2" and you should find something like this:

  compileSdkVersion 23
    buildToolsVersion "23.0.2"

set compileSdkVersion to 25 and buildToolsVersion as "25.0.0" or "25.0.3" or check your default version in your android studio by creating a project in app level build.gradle!!

this should work!!

if you still same issue, update your android studio and set up react native accordingly and try again!!

Hope it helps!!

**Comment by saeedvz** [comment]
Thanks. Solved my problem.
